# Generated by Django 5.2.14 on 2026-05-08 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Marcaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('R', 'Receso'), ('S', 'Salida')], max_length=1)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('ip_origen', models.GenericIPAddressField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asistencia.empleado')),
            ],
        ),
    ]
